import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '~/app/globals.css'
import '~/rpc/server'
import { Providers } from '~/app/providers'
import { Header } from '~/components/header'

const satoshiVariable = localFont({
  src: '../fonts/satoshi-variable.ttf',
  fallback: ['system-ui'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(
  props: Readonly<{
    children: React.ReactNode
  }>,
) {
  const { children } = props

  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={satoshiVariable.variable}
    >
      <body>
        <Providers>
          <main>
            <Header />

            <div>{children}</div>
          </main>
        </Providers>
      </body>
    </html>
  )
}
