import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import '~/app/globals.css'
import '~/rpc/server'
import { Providers } from '~/app/providers'

const manropeSans = Manrope({
  variable: '--font-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(
  props: Readonly<{
    children: React.ReactNode
  }>,
) {
  const { children } = props

  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={manropeSans.variable}
    >
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
