import type {
  FilterDataGenerated,
  FilterLocaleData,
} from '~/features/filter-builder/lib/types'

export function serializeFilterDataToTs(data: FilterDataGenerated): string {
  return [
    '// Auto-generated by build-filter-data. Do not edit manually.',
    '// Regenerate: pnpm start:dev build-filter-data',
    '',
    "import type { FilterDataGenerated } from '../features/filter-builder/lib/types'",
    '',
    `export const filterData = ${JSON.stringify(data, null, 2)} satisfies FilterDataGenerated`,
  ].join('\n')
}

export function serializeFilterLocaleToTs(
  _localeId: string,
  data: FilterLocaleData,
): string {
  return [
    '// Auto-generated by build-filter-data. Do not edit manually.',
    '// Regenerate: pnpm start:dev build-filter-data',
    '',
    "import type { FilterLocaleData } from '../../features/filter-builder/lib/types'",
    '',
    `export const filterLocale = ${JSON.stringify(data, null, 2)} satisfies FilterLocaleData`,
  ].join('\n')
}
