name: PR Preview Deployment - Web

permissions:
  pull-requests: write
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy-preview:
    uses: ./.github/workflows/build-and-deploy-preview.yml
    with:
      app: web
      name: Lumo Web
      enable-database: true
    secrets: inherit
