name: PR Preview Deployment - Storybook

permissions:
  pull-requests: write
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy-preview:
    uses: ./.github/workflows/build-and-deploy-preview.yml
    with:
      app: storybook
      name: Lumo Storybook
      enable-database: false
    secrets: inherit